version: '3.4'

services:
  ## Database ##
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  ## Service Bus ##
  rabbitmq:
    image: rabbitmq:3-management-alpine

  ## Internal API Services ##
  arbitrage.api:
    image: ${DOCKER_REGISTRY-}arbitrageapi
    build:
      context: .
      dockerfile: Services/Arbitrage/Arbitrage.API/Dockerfile
    depends_on:
      - rabbitmq

  sentiment.api:
    image: ${DOCKER_REGISTRY-}sentimentapi
    build:
      context: .
      dockerfile: Services/Sentiment/Sentiment.API/Dockerfile
    depends_on:
      - rabbitmq

  ## Public API Services ##
  trading-apigw:
    image: ${DOCKER_REGISTRY-}apigwbase
    build:
      context: .
      dockerfile: ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - arbitrage.api
      - sentiment.api
      - rabbitmq